# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

logger:
  default: info
  logs:
     custom_components.wiz_light: debug


light:
  - platform: wiz_light
    name: "Test1"
    host: 192.168.178.184
